n("", 64258, "Latin Small Ligature FL", ["", "64258", "FL", ""]);
n("", 64257, "Latin Small Ligature FI", ["FI"]);
n("", 8745, "Intersection", ["Intersection", "n"]);
n("", 8729, "Bullet Operator", ["Bullet", "*", "."]);
n("", 8710, "Increment", ["Increment", "triangle"]);
n("", 8542, "Vulgar Fraction Seven Eighths", ["Vulgar", "Fraction", "Seven", "Eighths", "7/8"]);
n("", 8541, "Vulgar Fraction Five Eighths", ["Vulgar", "Fraction", "Five", "Eighths", "5/8"]);
n("", 8540, "Vulgar Fraction Three Eighths", ["Vulgar", "Fraction", "Three", "Eighths", "3/8"]);
n("", 8539, "Vulgar Fraction One Eighth", ["Vulgar", "Fraction", "Eighth", "One", "1/8"]);
n("", 8494, "Estimated Symbol", ["Estimated", "e"]);
n("", 8486, "Ohm Sign (Ohm)", ["n", "Ohm"]);
n("", 8470, "Numero Sign (Numero)", ["Numero", "l"]);
n("", 8453, "Care Of", ["Care", "Of", "co", "c/o"]);
n("", 8359, "Peseta Sign", ["Peseta", "pts"]);
n("", 8356, "Lira Sign", ["Lira", "£"]);
n("", 8355, "French Franc Sign", ["French", "Franc", "F"]);
n("", 8319, "Superscript Latin Small Letter N", ["Superscript", "N"]);
n("", 8259, "Hyphen Bullet", ["Hyphen", "-", "Bullet"]);
n("", 8252, "Double Exclamation Mark", ["Double", "Exclamation", "Mark", "!!"]);
n("", 8233, "Paragraph Separator", ["Paragraph", "Separator"]);
n("", 8232, "Line Separator", ["Separator", "Line"]);
n("", 8227, "Triangular Bullet", ["Triangular", "Bullet", "triangle"]);
n("", 8219, "Single High-Reversed-9 Quotation Mark (Single Reversed Comma Quotation Mark)", ["Quotation", "Mark", "Reversed"]);
n("", 8215, "Double Low Line (Spacing Double Underscore)", ["Double", "Line", "Underscore", "_"]);
n("", 8213, "Horizontal Bar (Quotation Dash)", ["Horizontal", "-", "Bar", "Dash"]);
n("", 8208, "Hyphen", ["Hyphen", "-"]);
n("", 7923, "Latin Small Letter Y With Grave", ["", "7923", "Y", "Grave", ""]);
n("", 7922, "Latin Capital Letter Y With Grave", ["Y", "Grave"]);
n("", 7813, "Latin Small Letter W With Diaeresis", ["W", "Diaeresis"]);
n("", 7812, "Latin Capital Letter W With Diaeresis", ["W", "Diaeresis"]);
n("", 7811, "Latin Small Letter W With Acute", ["W", "Acute"]);
n("", 7810, "Latin Capital Letter W With Acute", ["W", "Acute"]);
n("", 7809, "Latin Small Letter W With Grave", ["W", "Grave"]);
n("", 7808, "Latin Capital Letter W With Grave", ["W", "Grave"]);
n("", 7787, "Latin Small Letter T With Dot Above", ["T", "Dot", "Above"]);
n("", 7786, "Latin Capital Letter T With Dot Above", ["T", "Dot", "Above"]);
n("", 7777, "Latin Small Letter S With Dot Above", ["S", "Dot", "Above"]);
n("", 7776, "Latin Capital Letter S With Dot Above", ["S", "Dot", "Above"]);
n("", 7767, "Latin Small Letter P With Dot Above", ["P", "Dot", "Above"]);
n("", 7766, "Latin Capital Letter P With Dot Above", ["P", "Dot", "Above"]);
n("", 7745, "Latin Small Letter M With Dot Above", ["M", "Dot", "Above"]);
n("", 7744, "Latin Capital Letter M With Dot Above", ["M", "Dot", "Above"]);
n("", 7729, "Latin Small Letter K With Acute", ["K", "Acute"]);
n("", 7728, "Latin Capital Letter K With Acute", ["K", "Acute"]);
n("", 7711, "Latin Small Letter F With Dot Above", ["F", "Dot", "Above"]);
n("", 7710, "Latin Capital Letter F With Dot Above", ["F", "Dot", "Above"]);
n("", 7697, "Latin Small Letter D With Cedilla", ["D", "Cedilla"]);
n("", 7696, "Latin Capital Letter D With Cedilla", ["D", "Cedilla"]);
n("", 7691, "Latin Small Letter D With Dot Above", ["D", "Dot", "Above"]);
n("", 7690, "Latin Capital Letter D With Dot Above", ["D", "Dot", "Above"]);
n("", 7683, "Latin Small Letter B With Dot Above", ["B", "Dot", "Above"]);
n("", 7682, "Latin Capital Letter B With Dot Above", ["B", "Dot", "Above"]);
n("", 733, "Double Acute Accent (Spacing Double Acute)", ["Acute", "Accent", "Double"]);
n("", 731, "Ogonek (Spacing Ogonek)", ["Ogonek", ","]);
n("", 730, "Ring Above (Spacing Ring Above)", ["Ring", "Above", "o"]);
n("", 729, "Dot Above (Spacing Dot Above)", ["Dot", "Above", "."]);
n("", 728, "Breve (Spacing Breve)", ["Breve", "^"]);
n("", 658, "Latin Small Letter Ezh (Small Yogh)", ["Ezh", "3", "z"]);
n("", 636, "Latin Small Letter R With Long Leg", ["R", "Leg"]);
n("", 511, "Latin Small Letter O With Stroke And Acute", ["O", "Stroke", "Acute"]);
n("", 510, "Latin Capital Letter O With Stroke And Acute", ["O", "Stroke", "Acute"]);
n("", 509, "Latin Small Letter AE With Acute", ["AE", "Acute"]);
n("", 508, "Latin Capital Letter AE With Acute", ["AE", "Acute"]);
n("", 507, "Latin Small Letter A With Ring Above And Acute", ["A", "Ring", "Above", "Acute"]);
n("", 506, "Latin Capital Letter A With Ring Above And Acute", ["A", "Ring", "Above", "Acute"]);
n("", 501, "Latin Small Letter G With Acute", ["G", "Acute"]);
n("", 500, "Latin Capital Letter G With Acute", ["G", "Acute"]);
n("", 499, "Latin Small Letter DZ", ["DZ"]);
n("", 497, "Latin Capital Letter DZ", ["DZ"]);
n("", 495, "Latin Small Letter Ezh With Caron (Small Yogh Hacek)", ["Ezh", "Caron", "Yogh", "Hacek"]);
n("", 494, "Latin Capital Letter Ezh With Caron (Capital Yogh Hacek)", ["Ezh", "Caron", "Yogh", "Hacek"]);
n("", 489, "Latin Small Letter K With Caron (Small K Hacek)", ["K", "Caron", "Hacek"]);
n("", 488, "Latin Capital Letter K With Caron (Capital K Hacek)", ["K", "Caron", "Hacek"]);
n("", 487, "Latin Small Letter G With Caron (Small G Hacek)", ["G", "Caron", "Hacek"]);
n("", 486, "Latin Capital Letter G With Caron (Capital G Hacek)", ["G", "Caron", "Hacek"]);
n("", 485, "Latin Small Letter G With Stroke (Small G Bar)", ["G", "Stroke", "Bar"]);
n("", 484, "Latin Capital Letter G With Stroke (Capital G Bar)", ["G", "Stroke", "Bar"]);
n("", 479, "Latin Small Letter A With Diaeresis And Macron (Small A Diaeresis Macron)", ["A", "Diaeresis", "Macron"]);
n("", 478, "Latin Capital Letter A With Diaeresis And Macron (Capital A Diaeresis Macron)", ["A", "Diaeresis", "Macron"]);
n("", 460, "Latin Small Letter NJ (Small N J)", ["NJ"]);
n("", 458, "Latin Capital Letter NJ (Capital N J)", ["NJ"]);
n("", 457, "Latin Small Letter LJ (Small L J)", ["LJ"]);
n("", 455, "Latin Capital Letter LJ (Capital L J)", ["LJ"]);
n("", 454, "Latin Small Letter DZ With Caron (Small D Z Hacek)", ["DZ", "Caron", "Hacek"]);
n("", 452, "Latin Capital Letter DZ With Caron (Capital D Z Hacek)", ["DZ", "Caron", "Hacek"]);
n("", 439, "Latin Capital Letter Ezh (Capital Yogh)", ["Ezh", "Yogh"]);
n("", 383, "Latin Small Letter Long S", ["Long", "S"]);
n("", 382, "Latin Small Letter Z With Caron (Small Z Hacek)", ["Z", "Caron", "Hacek"]);
n("", 381, "Latin Capital Letter Z With Caron (Capital Z Hacek)", ["Z", "Caron", "Hacek"]);
n("", 380, "Latin Small Letter Z With Dot Above (Small Z Dot)", ["Z", "Dot", "Above"]);
n("", 379, "Latin Capital Letter Z With Dot Above (Capital Z Dot)", ["Z", "Dot", "Above"]);
n("", 378, "Latin Small Letter Z With Acute (Small Z Acute)", ["Z", "Acute"]);
n("", 377, "Latin Capital Letter Z With Acute (Capital Z Acute)", ["Z", "Acute"]);
n("", 375, "Latin Small Letter Y With Circumflex (Small Y Circumflex)", ["Y", "Circumflex"]);
n("", 374, "Latin Capital Letter Y With Circumflex (Capital Y Circumflex)", ["Y", "Circumflex"]);
n("", 373, "Latin Small Letter W With Circumflex (Small W Circumflex)", ["W", "Circumflex"]);
n("", 372, "Latin Capital Letter W With Circumflex (Capital W Circumflex)", ["W", "Circumflex"]);
n("", 371, "Latin Small Letter U With Ogonek (Small U Ogonek)", ["U", "Ogonek"]);
n("", 370, "Latin Capital Letter U With Ogonek (Capital U Ogonek)", ["U", "Ogonek"]);
n("", 369, "Latin Small Letter U With Double Acute (Small U Double Acute)", ["U", "Double", "Acute"]);
n("", 368, "Latin Capital Letter U With Double Acute (Capital U Double Acute)", ["U", "Double", "Acute"]);
n("", 367, "Latin Small Letter U With Ring Above (Small U Ring)", ["U", "Ring", "Above"]);
n("", 366, "Latin Capital Letter U With Ring Above (Capital U Ring)", ["U", "Ring", "Above"]);
n("", 365, "Latin Small Letter U With Breve (Small U Breve)", ["U", "Breve"]);
n("", 364, "Latin Capital Letter U With Breve (Capital U Breve)", ["U", "Breve"]);
n("", 363, "Latin Small Letter U With Macron (Small U Macron)", ["U", "Macron"]);
n("", 362, "Latin Capital Letter U With Macron (Capital U Macron)", ["U", "Macron"]);
n("", 361, "Latin Small Letter U With Tilde (Small U Tilde)", ["U", "Tilde"]);
n("", 360, "Latin Capital Letter U With Tilde (Capital U Tilde)", ["U", "Tilde"]);
n("", 359, "Latin Small Letter T With Stroke (Small T Bar)", ["T", "Stroke", "bar"]);
n("", 358, "Latin Capital Letter T With Stroke (Capital T Bar)", ["T", "Stroke", "bar"]);
n("", 357, "Latin Small Letter T With Caron (Small T Hacek)", ["T", "Caron"]);
n("", 356, "Latin Capital Letter T With Caron (Capital T Hacek)", ["T", "Caron"]);
n("", 355, "Latin Small Letter T With Cedilla (Small T Cedilla)", ["T", "Cedilla"]);
n("", 354, "Latin Capital Letter T With Cedilla (Capital T Cedilla)", ["T", "Cedilla"]);
n("", 351, "Latin Small Letter S With Cedilla (Small S Cedilla)", ["S", "Cedilla"]);
n("", 350, "Latin Capital Letter S With Cedilla (Capital S Cedilla)", ["S", "Cedilla"]);
n("", 349, "Latin Small Letter S With Circumflex (Small S Circumflex)", ["S", "Circumflex"]);
n("", 348, "Latin Capital Letter S With Circumflex (Capital S Circumflex)", ["S", "Circumflex"]);
n("", 347, "Latin Small Letter S With Acute (Small S Acute)", ["S", "Acute"]);
n("", 346, "Latin Capital Letter S With Acute (Capital S Acute)", ["S", "Acute"]);
n("", 345, "Latin Small Letter R With Caron (Small R Hacek)", ["R", "Caron"]);
n("", 344, "Latin Capital Letter R With Caron (Capital R Hacek)", ["R", "Caron"]);
n("", 343, "Latin Small Letter R With Cedilla (Small R Cedilla)", ["R", "Cedilla"]);
n("", 342, "Latin Capital Letter R With Cedilla (Capital R Cedilla)", ["R", "Cedilla"]);
n("", 341, "Latin Small Letter R With Acute (Small R Acute)", ["R", "Acute"]);
n("", 340, "Latin Capital Letter R With Acute (Capital R Acute)", ["R", "Acute"]);
n("", 337, "Latin Small Letter O With Double Acute (Small O Double Acute)", ["O", "Double", "Acute"]);
n("", 336, "Latin Capital Letter O With Double Acute (Capital O Double Acute)", ["O", "Double", "Acute"]);
n("", 335, "Latin Small Letter O With Breve (Small O Breve)", ["O", "Breve"]);
n("", 334, "Latin Capital Letter O With Breve (Capital O Breve)", ["O", "Breve"]);
n("", 333, "Latin Small Letter O With Macron (Small O Macron)", ["O", "Macron"]);
n("", 332, "Latin Capital Letter O With Macron (Capital O Macron)", ["O", "Macron"]);
n("", 331, "Latin Small Letter Eng", ["n", "Eng"]);
n("", 330, "Latin Capital Letter Eng", ["Eng", "n"]);
n("", 329, "Latin Small Letter N Preceded By Apostrophe (Small Apostrophe N)", ["N", "Preceded", "Apostrophe"]);
n("", 328, "Latin Small Letter N With Caron (Small N Hacek)", ["N", "Caron"]);
n("", 327, "Latin Capital Letter N With Caron (Capital N Hacek)", ["N", "Caron"]);
n("", 326, "Latin Small Letter N With Cedilla (Small N Cedilla)", ["N", "Cedilla"]);
n("", 325, "Latin Capital Letter N With Cedilla (Capital N Cedilla)", ["N", "Cedilla"]);
n("", 324, "Latin Small Letter N With Acute (Small N Acute)", ["N", "Acute"]);
n("", 323, "Latin Capital Letter N With Acute (Capital N Acute)", ["N", "Acute"]);
n("", 322, "Latin Small Letter L With Stroke (Small L Slash)", ["L", "Stroke", "Slash"]);
n("", 321, "Latin Capital Letter L With Stroke (Capital L Slash)", ["L", "Stroke", "Slash"]);
n("", 320, "Latin Small Letter L With Middle Dot", ["L", "Middle", "Dot"]);
n("", 319, "Latin Capital Letter L With Middle Dot", ["L", "Dot", "Middle"]);
n("", 318, "Latin Small Letter L With Caron (Small L Hacek)", ["L", "Caron"]);
n("", 317, "Latin Capital Letter L With Caron (Capital L Hacek)", ["L", "Caron"]);
n("", 316, "Latin Small Letter L With Cedilla (Small L Cedilla)", ["L", "Cedilla"]);
n("", 315, "Latin Capital Letter L With Cedilla (Capital L Cedilla)", ["L", "Cedilla"]);
n("", 314, "Latin Small Letter L With Acute (Small L Acute)", ["L", "Acute"]);
n("", 313, "Latin Capital Letter L With Acute (Capital L Acute)", ["L", "Acute"]);
n("", 312, "Latin Small Letter Kra", ["Kra", "k"]);
n("", 311, "Latin Small Letter K With Cedilla (Small K Cedilla)", ["K", "Cedilla"]);
n("", 310, "Latin Capital Letter K With Cedilla (Capital K Cedilla)", ["K", "Cedilla"]);
n("", 309, "Latin Small Letter J With Circumflex (Small J Circumflex)", ["J", "Circumflex"]);
n("", 308, "Latin Capital Letter J With Circumflex (Capital J Circumflex)", ["J", "Circumflex"]);
n("", 307, "Latin Small Ligature IJ (Small I J)", ["Ligature", "IJ"]);
n("", 306, "Latin Capital Ligature IJ (Capital I J)", ["IJ", "Ligature"]);
n("", 305, "Latin Small Letter Dotless I", ["Dotless", "I"]);
n("", 304, "Latin Capital Letter I With Dot Above (Capital I Dot)", ["I", "Dot"]);
n("", 303, "Latin Small Letter I With Ogonek (Small I Ogonek)", ["I", "Ogonek"]);
n("", 302, "Latin Capital Letter I With Ogonek (Capital I Ogonek)", ["I", "Ogonek"]);
n("", 301, "Latin Small Letter I With Breve (Small I Breve)", ["I", "Breve"]);
n("", 300, "Latin Capital Letter I With Breve (Capital I Breve)", ["I", "Breve"]);
n("", 299, "Latin Small Letter I With Macron (Small I Macron)", ["I", "Macron"]);
n("", 298, "Latin Capital Letter I With Macron (Capital I Macron)", ["I", "Macron"]);
n("", 297, "Latin Small Letter I With Tilde (Small I Tilde)", ["I", "Tilde"]);
n("", 296, "Latin Capital Letter I With Tilde (Capital I Tilde)", ["I", "Tilde"]);
n("", 295, "Latin Small Letter H With Stroke (Small H Bar)", ["Stroke", "H", "Bar"]);
n("", 294, "Latin Capital Letter H With Stroke (Capital H Bar)", ["H", "Bar", "Stroke"]);
n("", 293, "Latin Small Letter H With Circumflex (Small H Circumflex)", ["H", "Circumflex"]);
n("", 292, "Latin Capital Letter H With Circumflex (Capital H Circumflex)", ["H", "Circumflex"]);
n("", 291, "Latin Small Letter G With Cedilla (Small G Cedilla)", ["G", "Cedilla"]);
n("", 290, "Latin Capital Letter G With Cedilla (Capital G Cedilla)", ["G", "Cedilla"]);
n("", 289, "Latin Small Letter G With Dot Above (Small G Dot)", ["G", "Dot"]);
n("", 288, "Latin Capital Letter G With Dot Above (Capital G Dot)", ["G", "Dot"]);
n("", 287, "Latin Small Letter G With Breve (Small G Breve)", ["G", "Breve"]);
n("", 286, "Latin Capital Letter G With Breve (Capital G Breve)", ["G", "Breve"]);
n("", 285, "Latin Small Letter G With Circumflex (Small G Circumflex)", ["G", "Circumflex"]);
n("", 284, "Latin Capital Letter G With Circumflex (Capital G Circumflex)", ["G", "Circumflex"]);
n("", 283, "Latin Small Letter E With Caron (Small E Hacek)", ["E", "Caron"]);
n("", 282, "Latin Capital Letter E With Caron (Capital E Hacek)", ["E", "Caron"]);
n("", 281, "Latin Small Letter E With Ogonek (Small E Ogonek)", ["E", "Ogonek"]);
n("", 280, "Latin Capital Letter E With Ogonek (Capital E Ogonek)", ["E", "Ogonek"]);
n("", 279, "Latin Small Letter E With Dot Above (Small E Dot)", ["E", "Dot"]);
n("", 278, "Latin Capital Letter E With Dot Above (Capital E Dot)", ["E", "Dot"]);
n("", 277, "Latin Small Letter E With Breve (Small E Breve)", ["E", "Breve"]);
n("", 276, "Latin Capital Letter E With Breve (Capital E Breve)", ["E", "Breve"]);
n("", 275, "Latin Small Letter E With Macron (Small E Macron)", ["E", "Macron"]);
n("", 274, "Latin Capital Letter E With Macron (Capital E Macron)", ["E", "Macron"]);
n("", 273, "Latin Small Letter D With Stroke (Small D Bar)", ["D", "Stroke"]);
n("", 272, "Latin Capital Letter D With Stroke (Capital D Bar)", ["D", "Stroke"]);
n("", 271, "Latin Small Letter D With Caron (Small D Hacek)", ["D", "Caron"]);
n("", 270, "Latin Capital Letter D With Caron (Capital D Hacek)", ["D", "Caron"]);
n("", 269, "Latin Small Letter C With Caron (Small C Hacek)", ["C", "Caron"]);
n("", 268, "Latin Capital Letter C With Caron (Capital C Hacek)", ["C", "Caron"]);
n("", 267, "Latin Small Letter C With Dot Above (Small C Dot)", ["C", "Dot"]);
n("", 266, "Latin Capital Letter C With Dot Above (Capital C Dot)", ["C", "Dot"]);
n("", 265, "Latin Small Letter C With Circumflex (Small C Circumflex)", ["C", "Circumflex)"]);
n("", 264, "Latin Capital Letter C With Circumflex (Capital C Circumflex)", ["C", "Circumflex"]);
n("", 263, "Latin Small Letter C With Acute (Small C Acute)", ["C", "Acute"]);
n("", 262, "Latin Capital Letter C With Acute (Capital C Acute)", ["C", "Acute"]);
n("", 261, "Latin Small Letter A With Ogonek (Small A Ogonek)", ["A", "Ogonek"]);
n("", 260, "Latin Capital Letter A With Ogonek (Capital A Ogonek)", ["A", "Ogonek"]);
n("", 259, "Latin Small Letter A With Breve (Small A Breve)", ["Breve", "A"]);
n("", 258, "Latin Capital Letter A With Breve (Capital A Breve)", ["Breve", "A"]);
n("", 257, "Latin Small Letter A With Macron (Small A Macron)", ["Macron", "A"]);
n("", 256, "Latin Capital Letter A With Macron (Capital A Macron)", ["", "256", "Macron", "A", ""]);